# -*- coding: utf-8 -*-
# Diccionario del crucigrama.
# Formato: (RESPUESTA, pista, nivel, tema)
# - RESPUESTA: mayúsculas, sin tildes (la Ñ sí se conserva)
# - nivel: 1 = fácil, 2 = medio, 3 = difícil
# - tema: música, fútbol, tecnología, historia, cine/tv, comida, geografía,
#         ciencia, deporte, actualidad, general

WORDS = [
    # ---------- FÚTBOL ----------
    ("GOL", "Máxima alegría del fútbol.", 1, "fútbol"),
    ("PENAL", "Falta que se ejecuta desde los doce pasos.", 1, "fútbol"),
    ("MESSI", "Astro argentino, campeón del mundo en Qatar 2022.", 1, "fútbol"),
    ("PELE", "O Rei, tricampeón mundial con Brasil.", 1, "fútbol"),
    ("BOCA", "Club argentino dueño de la Bombonera.", 1, "fútbol"),
    ("RIVER", "Clásico rival de Boca Juniors.", 1, "fútbol"),
    ("FIFA", "Organismo rector del fútbol mundial.", 1, "fútbol"),
    ("VAR", "Videoarbitraje del fútbol, por su sigla en inglés.", 1, "fútbol"),
    ("CORNER", "Tiro de esquina.", 1, "fútbol"),
    ("ARQUERO", "Único jugador que puede usar las manos.", 1, "fútbol"),
    ("MARADONA", "Autor de la 'mano de Dios' en México 86.", 1, "fútbol"),
    ("ALEXIS", "__ Sánchez, el Niño Maravilla del fútbol chileno.", 2, "fútbol"),
    ("VIDAL", "Arturo __, el 'Rey Arturo' del mediocampo chileno.", 2, "fútbol"),
    ("ZAMORANO", "Iván __, 'Bam Bam', ídolo chileno del Inter de Milán.", 2, "fútbol"),
    ("COLOCOLO", "El 'Cacique', club más popular de Chile.", 2, "fútbol"),
    ("CHILENA", "Remate acrobático de espaldas al arco.", 2, "fútbol"),
    ("BRAVO", "Claudio __, arquero campeón de América con Chile.", 2, "fútbol"),
    ("KEMPES", "Matador argentino, goleador del Mundial 1978.", 3, "fútbol"),
    ("LABRUNA", "Ángel __, máximo ídolo histórico de River Plate.", 3, "fútbol"),
    ("CANIGGIA", "El 'Pájaro' del gol argentino a Brasil en Italia 90.", 3, "fútbol"),
    ("ELIAS", "Don __ Figueroa, tres veces mejor jugador de América.", 3, "fútbol"),

    # ---------- MÚSICA ----------
    ("TANGO", "Género rioplatense que se baila abrazado.", 1, "música"),
    ("ROCK", "Género musical de guitarras eléctricas.", 1, "música"),
    ("PIANO", "Instrumento de teclas blancas y negras.", 1, "música"),
    ("OPERA", "Género lírico que se canta en teatros.", 1, "música"),
    ("CUMBIA", "Ritmo tropical infaltable en las fiestas.", 1, "música"),
    ("SHAKIRA", "Cantante colombiana del 'Waka Waka'.", 1, "música"),
    ("JAZZ", "Género de la improvisación, nacido en Nueva Orleans.", 1, "música"),
    ("CORO", "Conjunto de voces que cantan juntas.", 1, "música"),
    ("GARDEL", "El 'Zorzal Criollo', voz eterna del tango.", 2, "música"),
    ("CUECA", "Baile nacional de Chile, con pañuelo.", 2, "música"),
    ("CERATI", "Gustavo __, líder de Soda Stereo.", 2, "música"),
    ("SODA", "__ Stereo, banda de 'De Música Ligera'.", 2, "música"),
    ("JARA", "Víctor __, cantautor chileno de 'Te Recuerdo Amanda'.", 2, "música"),
    ("FITO", "__ Páez, autor de 'El Amor Después del Amor'.", 2, "música"),
    ("CHARLY", "__ García, prócer del rock argentino.", 2, "música"),
    ("DUKI", "Pionero del trap argentino.", 2, "música"),
    ("BIZARRAP", "Productor argentino de las 'Music Sessions'.", 2, "música"),
    ("LAFERTE", "Mon __, cantante chilena radicada en México.", 2, "música"),
    ("QUILAPAYUN", "Grupo chileno de la Nueva Canción, de negro poncho.", 3, "música"),
    ("SPINETTA", "El 'Flaco' de Almendra e Invisible.", 3, "música"),
    ("VIOLETA", "__ Parra, autora de 'Gracias a la Vida'.", 2, "música"),
    ("ARIA", "Pieza de ópera para voz solista.", 3, "música"),

    # ---------- TECNOLOGÍA ----------
    ("APPLE", "Empresa creadora del iPhone.", 1, "tecnología"),
    ("WIFI", "Conexión inalámbrica a internet.", 1, "tecnología"),
    ("APP", "Programa que se instala en el celular.", 1, "tecnología"),
    ("CHIP", "Pequeño circuito integrado.", 1, "tecnología"),
    ("MOUSE", "Ratón del computador.", 1, "tecnología"),
    ("PIXEL", "Punto mínimo de una imagen digital.", 1, "tecnología"),
    ("ROBOT", "Máquina que automatiza tareas.", 1, "tecnología"),
    ("DRON", "Aeronave no tripulada que se pilotea a distancia.", 1, "tecnología"),
    ("LASER", "Rayo de luz coherente usado en cirugía.", 1, "tecnología"),
    ("GOOGLE", "El buscador más usado del mundo.", 1, "tecnología"),
    ("NUBE", "Ahí se guardan los archivos en internet.", 1, "tecnología"),
    ("EMAIL", "Correo electrónico.", 1, "tecnología"),
    ("TIKTOK", "Red social de videos cortos.", 1, "tecnología"),
    ("CHATBOT", "Programa que conversa por chat.", 1, "tecnología"),
    ("ANDROID", "Sistema operativo móvil de Google.", 2, "tecnología"),
    ("WHATSAPP", "App de mensajería más usada en Chile y Argentina.", 1, "tecnología"),
    ("INSTAGRAM", "Red social de fotos con filtros e historias.", 1, "tecnología"),
    ("BLUETOOTH", "Conexión inalámbrica de corto alcance.", 2, "tecnología"),
    ("SERVIDOR", "Computador que aloja sitios web.", 2, "tecnología"),
    ("ALGORITMO", "Secuencia de pasos que sigue un programa.", 2, "tecnología"),
    ("TURING", "Alan __, padre de la computación.", 3, "tecnología"),
    ("BINARIO", "Sistema numérico de unos y ceros.", 2, "tecnología"),

    # ---------- HISTORIA ----------
    ("INCA", "Imperio andino con capital en Cusco.", 1, "historia"),
    ("ROMA", "Imperio de los Césares.", 1, "historia"),
    ("EGIPTO", "País de las pirámides y los faraones.", 1, "historia"),
    ("COLON", "Navegante que llegó a América en 1492.", 1, "historia"),
    ("MAYA", "Cultura mesoamericana de Chichén Itzá.", 1, "historia"),
    ("AZTECA", "Imperio de Tenochtitlán.", 1, "historia"),
    ("PERON", "Juan Domingo __, tres veces presidente argentino.", 2, "historia"),
    ("EVITA", "Apodo de Eva Duarte de Perón.", 2, "historia"),
    ("OHIGGINS", "Padre de la Patria chilena (sin apóstrofe).", 2, "historia"),
    ("ALLENDE", "Presidente chileno derrocado en 1973.", 2, "historia"),
    ("NAPOLEON", "Emperador francés derrotado en Waterloo.", 2, "historia"),
    ("PRAT", "Arturo __, héroe naval de Iquique.", 2, "historia"),
    ("MAPUCHE", "Pueblo originario del sur de Chile y Argentina.", 2, "historia"),
    ("BOLIVAR", "Libertador venezolano de media Sudamérica.", 2, "historia"),
    ("CAUPOLICAN", "Toqui mapuche que cargó el tronco en La Araucana.", 3, "historia"),
    ("LAUTARO", "Joven toqui que venció a Valdivia en Tucapel.", 3, "historia"),
    ("SARMIENTO", "Prócer argentino de la educación, cara de los billetes.", 3, "historia"),
    ("ESPARTA", "Ciudad griega de guerreros legendarios.", 2, "historia"),
    ("VIKINGO", "Navegante nórdico que asoló Europa medieval.", 1, "historia"),
    ("FARAON", "Monarca del antiguo Egipto.", 1, "historia"),

    # ---------- CINE / TV ----------
    ("OSCAR", "Estatuilla dorada de Hollywood.", 1, "cine/tv"),
    ("TITANIC", "Filme de James Cameron sobre un naufragio famoso.", 1, "cine/tv"),
    ("SHREK", "Ogro verde del cine de animación.", 1, "cine/tv"),
    ("NETFLIX", "Plataforma de streaming pionera.", 1, "cine/tv"),
    ("HOMERO", "Padre de la familia Simpson.", 1, "cine/tv"),
    ("BATMAN", "El Caballero de la Noche de Ciudad Gótica.", 1, "cine/tv"),
    ("AVATAR", "Filme de Cameron ambientado en Pandora.", 1, "cine/tv"),
    ("CHAVO", "El __ del Ocho, vecino del barril.", 1, "cine/tv"),
    ("DARIN", "Ricardo __, actor de 'El Secreto de sus Ojos'.", 2, "cine/tv"),
    ("FRANCELLA", "Guillermo __, protagonista de 'El Encargado'.", 2, "cine/tv"),
    ("CONDORITO", "Historieta chilena creada por Pepo.", 2, "cine/tv"),
    ("MARVEL", "Estudio de los Avengers.", 1, "cine/tv"),
    ("SERIE", "Historia televisiva por capítulos.", 1, "cine/tv"),
    ("ACTOR", "Intérprete de personajes.", 1, "cine/tv"),
    ("CINE", "Sala de la pantalla grande.", 1, "cine/tv"),
    ("KUBRICK", "Director de '2001: Odisea del Espacio'.", 3, "cine/tv"),
    ("FELLINI", "Director italiano de 'La Dolce Vita'.", 3, "cine/tv"),
    ("SANDRINI", "Luis __, cómico clásico del cine argentino.", 3, "cine/tv"),

    # ---------- COMIDA ----------
    ("ASADO", "Reunión argentina alrededor de la parrilla.", 1, "comida"),
    ("MATE", "Infusión rioplatense que se toma con bombilla.", 1, "comida"),
    ("EMPANADA", "Masa rellena; en Chile, de pino.", 1, "comida"),
    ("PIZZA", "Redonda, con queso y de origen italiano.", 1, "comida"),
    ("SUSHI", "Bocado japonés de arroz y pescado.", 1, "comida"),
    ("TACO", "Tortilla mexicana doblada y rellena.", 1, "comida"),
    ("PALTA", "Aguacate, en Chile y Argentina.", 1, "comida"),
    ("MANJAR", "Dulce de leche, en Chile.", 1, "comida"),
    ("CHOCLO", "Maíz tierno, en el cono sur.", 1, "comida"),
    ("ALFAJOR", "Dulce relleno, clásico del kiosco argentino.", 1, "comida"),
    ("CHORIPAN", "Clásico sándwich de las canchas argentinas.", 1, "comida"),
    ("PISCO", "Destilado disputado entre Chile y Perú.", 2, "comida"),
    ("CAZUELA", "Guiso chileno con presa, papa y choclo.", 2, "comida"),
    ("CEVICHE", "Pescado marinado en limón.", 1, "comida"),
    ("PAELLA", "Arroz español con azafrán.", 1, "comida"),
    ("TERREMOTO", "Trago chileno con pipeño y helado de piña.", 2, "comida"),
    ("SOPAIPILLA", "Fritura chilena de zapallo para días de lluvia.", 2, "comida"),
    ("MALBEC", "Cepa insignia del vino argentino.", 2, "comida"),
    ("CARMENERE", "Cepa emblemática del vino chileno.", 2, "comida"),
    ("MILANESA", "Filete empanizado, orgullo argentino.", 1, "comida"),
    ("PEBRE", "Salsa chilena de tomate, cebolla y cilantro.", 2, "comida"),
    ("CURANTO", "Cocción chilota en hoyo con piedras calientes.", 3, "comida"),
    ("LOCRO", "Guiso norteño argentino del 25 de Mayo.", 2, "comida"),
    ("UMAMI", "El quinto sabor.", 3, "comida"),

    # ---------- GEOGRAFÍA ----------
    ("ANDES", "Cordillera que separa Chile y Argentina.", 1, "geografía"),
    ("ATACAMA", "El desierto más árido del mundo.", 1, "geografía"),
    ("PARIS", "Capital de la Torre Eiffel.", 1, "geografía"),
    ("NILO", "Río que atraviesa Egipto.", 1, "geografía"),
    ("ASIA", "Continente más poblado.", 1, "geografía"),
    ("TOKIO", "Capital de Japón.", 1, "geografía"),
    ("PATAGONIA", "Región austral compartida por Chile y Argentina.", 1, "geografía"),
    ("MENDOZA", "Ciudad argentina famosa por sus viñedos.", 1, "geografía"),
    ("VALPARAISO", "Puerto principal y ciudad patrimonial de Chile.", 2, "geografía"),
    ("RAPANUI", "Nombre polinésico de la Isla de Pascua.", 2, "geografía"),
    ("OSORNO", "Volcán y ciudad del sur de Chile.", 2, "geografía"),
    ("ACONCAGUA", "La cumbre más alta de América.", 2, "geografía"),
    ("TITICACA", "Lago navegable más alto del mundo.", 2, "geografía"),
    ("BARILOCHE", "Ciudad argentina de lagos, chocolate y esquí.", 1, "geografía"),
    ("USHUAIA", "Ciudad argentina del fin del mundo.", 2, "geografía"),
    ("SAHARA", "Gran desierto africano.", 1, "geografía"),
    ("EVEREST", "Techo del mundo, en el Himalaya.", 1, "geografía"),
    ("CHILOE", "Isla chilena de palafitos y mitología.", 2, "geografía"),
    ("PAMPA", "Llanura argentina de gauchos.", 1, "geografía"),
    ("DELTA", "Desembocadura de un río en brazos, como el Paraná.", 2, "geografía"),
    ("OASIS", "Vergel en medio del desierto.", 1, "geografía"),
    ("FIORDO", "Entrada de mar entre montañas, típica del sur austral.", 2, "geografía"),
    ("ELQUI", "Valle chileno de cielos estrellados y pisco.", 3, "geografía"),
    ("IGUAZU", "Cataratas compartidas por Argentina y Brasil.", 1, "geografía"),

    # ---------- CIENCIA / NATURALEZA ----------
    ("ATOMO", "Unidad básica de la materia.", 1, "ciencia"),
    ("LUNA", "Satélite natural de la Tierra.", 1, "ciencia"),
    ("MARTE", "El planeta rojo.", 1, "ciencia"),
    ("SOL", "Estrella del sistema solar.", 1, "ciencia"),
    ("ADN", "Molécula de la herencia.", 1, "ciencia"),
    ("PUMA", "Felino de los Andes.", 1, "ciencia"),
    ("CONDOR", "Ave emblemática de la cordillera.", 1, "ciencia"),
    ("COPIHUE", "Flor nacional de Chile.", 2, "ciencia"),
    ("OXIGENO", "Gas esencial para respirar.", 1, "ciencia"),
    ("NEWTON", "Físico de la ley de gravitación universal.", 2, "ciencia"),
    ("EINSTEIN", "Autor de la teoría de la relatividad.", 1, "ciencia"),
    ("CELULA", "Unidad mínima de los seres vivos.", 1, "ciencia"),
    ("IMAN", "Atrae al hierro.", 1, "ciencia"),
    ("ECLIPSE", "La Luna tapa al Sol, o al revés.", 1, "ciencia"),
    ("GEN", "Fragmento de ADN que se hereda.", 2, "ciencia"),
    ("NEURONA", "Célula del sistema nervioso.", 2, "ciencia"),
    ("DARWIN", "Naturalista de la evolución que visitó Chile.", 2, "ciencia"),
    ("ÑANDU", "Ave corredora de las pampas, parecida al avestruz.", 2, "ciencia"),
    ("QUARK", "Partícula elemental que forma protones.", 3, "ciencia"),
    ("ENZIMA", "Proteína que acelera reacciones químicas.", 3, "ciencia"),
    ("HUEMUL", "Ciervo del escudo chileno.", 2, "ciencia"),
    ("GALAXIA", "Conjunto de millones de estrellas, como la Vía Láctea.", 1, "ciencia"),

    # ---------- DEPORTE (otros) ----------
    ("TENIS", "Deporte de raquetas y sets.", 1, "deporte"),
    ("BOXEO", "Deporte de guantes y cuerdas.", 1, "deporte"),
    ("GOLF", "Deporte de hoyos y palos.", 1, "deporte"),
    ("JUDO", "Arte marcial japonés de llaves y caídas.", 1, "deporte"),
    ("RUGBY", "Deporte de los Pumas argentinos.", 1, "deporte"),
    ("MARATON", "Carrera de 42 kilómetros.", 1, "deporte"),
    ("MASSU", "Nicolás __, doble oro olímpico chileno en Atenas 2004.", 2, "deporte"),
    ("VILAS", "Guillermo __, leyenda del tenis argentino.", 2, "deporte"),
    ("GINOBILI", "Manu del básquet argentino, campeón NBA.", 2, "deporte"),
    ("GONZALEZ", "Fernando __, 'Mano de Piedra' del tenis chileno.", 2, "deporte"),
    ("AJEDREZ", "Juego de reyes, torres y alfiles.", 1, "deporte"),
    ("JAQUE", "Amenaza directa al rey en el tablero.", 2, "deporte"),
    ("SURF", "Deporte de olas y tabla.", 1, "deporte"),
    ("REMO", "Deporte de botes y paladas.", 2, "deporte"),

    # ---------- ACTUALIDAD ----------
    ("MILEI", "Presidente argentino elegido en 2023.", 1, "actualidad"),
    ("BORIC", "Presidente chileno del período 2022-2026.", 1, "actualidad"),
    ("STREAMER", "Transmite en vivo por Twitch o YouTube.", 1, "actualidad"),
    ("PODCAST", "Programa de audio por internet, a la carta.", 1, "actualidad"),
    ("EMOJI", "Carita o dibujito de los mensajes de texto.", 1, "actualidad"),
    ("VIRAL", "Así queda un video que todos comparten.", 1, "actualidad"),
    ("METAVERSO", "Mundo virtual que promocionó Zuckerberg.", 2, "actualidad"),
    ("BITCOIN", "La criptomoneda original.", 2, "actualidad"),
    ("INFLUENCER", "Vive de recomendar cosas en redes.", 1, "actualidad"),

    # ---------- GENERAL (conectores) ----------
    ("ORO", "Metal de los campeones.", 1, "general"),
    ("ECO", "Repetición del sonido.", 1, "general"),
    ("OSO", "Plantígrado que hiberna.", 1, "general"),
    ("ALA", "Le permite volar al ave.", 1, "general"),
    ("OLA", "Ondulación del mar.", 1, "general"),
    ("MAR", "Lo cruzan los barcos.", 1, "general"),
    ("RIO", "Corriente de agua dulce.", 1, "general"),
    ("ISLA", "Tierra rodeada de agua.", 1, "general"),
    ("MAPA", "Representación de un territorio.", 1, "general"),
    ("LATA", "Envase de las conservas; también, aburrimiento.", 1, "general"),
    ("TAZA", "Ahí se sirve el té.", 1, "general"),
    ("PERA", "Fruta de forma acampanada.", 1, "general"),
    ("UVA", "Fruta de la vendimia.", 1, "general"),
    ("AJO", "Diente que condimenta.", 1, "general"),
    ("SAL", "Condimento del salero.", 1, "general"),
    ("PAN", "Sale caliente de la panadería.", 1, "general"),
    ("LEON", "El rey de la selva.", 1, "general"),
    ("TIGRE", "Felino de rayas.", 1, "general"),
    ("NIDO", "Casa del pájaro.", 1, "general"),
    ("LUZ", "La dan las ampolletas.", 1, "general"),
    ("TREN", "Transporte de rieles y vagones.", 1, "general"),
    ("BARCO", "Navega por el mar.", 1, "general"),
    ("TORRE", "Pieza de ajedrez que va por las esquinas.", 1, "general"),
    ("PUENTE", "Une las dos orillas.", 1, "general"),
    ("ANCLA", "Fija el barco al fondo.", 1, "general"),
    ("ARENA", "Cubre la playa.", 1, "general"),
    ("VELA", "Ilumina cuando se corta la luz.", 1, "general"),
    ("RELOJ", "Marca las horas en la muñeca.", 1, "general"),
    ("LLAVE", "Abre la cerradura.", 1, "general"),
    ("ESPEJO", "Devuelve tu imagen.", 1, "general"),
    ("SOMBRA", "Te sigue en los días de sol.", 1, "general"),
    ("AROMA", "Olor agradable.", 1, "general"),
    ("ENIGMA", "Misterio difícil de descifrar.", 2, "general"),
    ("AZAR", "Lo que decide la suerte.", 2, "general"),
    ("ORACULO", "Respondía las consultas en Delfos.", 3, "general"),
    ("EFIMERO", "Que dura muy poco.", 3, "general"),
    ("ANAGRAMA", "Palabra formada reordenando las letras de otra.", 3, "general"),
    ("ALQUIMIA", "Antecesora esotérica de la química.", 3, "general"),
    ("ZODIACO", "Franja celeste de los doce signos.", 2, "general"),
    ("ESFINGE", "Guardiana de enigmas con cuerpo de león.", 3, "general"),
    ("LABERINTO", "De ahí no salía nadie sin el hilo de Ariadna.", 2, "general"),
    ("PANAL", "Casa hexagonal de las abejas.", 2, "general"),
    ("ORILLA", "Borde del río o del mar.", 1, "general"),
    ("SIESTA", "Sueño corto después de almuerzo.", 1, "general"),
    ("FERIA", "Mercado callejero de frutas y verduras.", 1, "general"),
    ("MICRO", "Bus urbano, en Chile.", 2, "general"),
    ("PEATON", "Cruza por el paso de cebra.", 1, "general"),
    ("BUZON", "Ahí se echan las cartas.", 1, "general"),
    ("FARO", "Guía a los barcos con su luz.", 1, "general"),
    ("VOLANTIN", "Cometa que se eleva en septiembre en Chile.", 2, "general"),

    # ---------- ARTE ----------
    ("DALI", "Pintor surrealista de los relojes derretidos.", 1, "arte"),
    ("PICASSO", "Pintor malagueño del Guernica.", 1, "arte"),
    ("FRIDA", "__ Kahlo, pintora mexicana de los autorretratos.", 1, "arte"),
    ("MONET", "Impresionista francés de los nenúfares.", 2, "arte"),
    ("VANGOGH", "Pintor de 'La Noche Estrellada' (junto).", 2, "arte"),
    ("BOTERO", "Escultor colombiano de figuras voluminosas.", 2, "arte"),
    ("MUSEO", "Casa de las obras de arte.", 1, "arte"),
    ("OLEO", "Pintura clásica sobre lienzo.", 2, "arte"),
    ("MURAL", "Pintura hecha directamente en la pared.", 1, "arte"),
    ("LOUVRE", "Museo parisino de la Gioconda.", 2, "arte"),
    ("VENUS", "La __ de Milo, escultura sin brazos.", 2, "arte"),
    ("MATTA", "Roberto __, pintor surrealista chileno.", 3, "arte"),
    ("BANKSY", "Grafitero británico de identidad secreta.", 2, "arte"),
    ("QUINO", "Creador de Mafalda.", 2, "arte"),
    ("MAFALDA", "Niña de historieta que odia la sopa.", 1, "arte"),

    # ---------- SERIES ----------
    ("FRIENDS", "Sitcom de seis amigos en Nueva York.", 1, "series"),
    ("SHELDON", "Físico peculiar de 'The Big Bang Theory'.", 2, "series"),
    ("MERLINA", "Hija de los Addams con serie propia en Netflix.", 1, "series"),
    ("OKUPAS", "Serie argentina de culto estrenada en 2000.", 3, "series"),
    ("SEINFELD", "Sitcom 'sobre nada' de los años 90.", 2, "series"),
    ("SOPRANO", "Tony __, mafioso de culto de HBO.", 2, "series"),
    ("ANIME", "Animación japonesa.", 1, "series"),
    ("POKEMON", "Pikachu es el más famoso de estos monstruos de bolsillo.", 1, "series"),
    ("NOVELA", "Drama televisivo de la tarde, en capítulos.", 1, "series"),

    # ---------- PELÍCULAS ----------
    ("MATRIX", "Filme donde Neo elige la pastilla roja.", 1, "cine/tv"),
    ("ROCKY", "Boxeador de Stallone en Filadelfia.", 1, "cine/tv"),
    ("GODZILLA", "Monstruo gigante japonés del cine.", 1, "cine/tv"),
    ("AMELIE", "Soñadora parisina del cine francés.", 2, "cine/tv"),
    ("PARASITOS", "Filme coreano ganador del Óscar 2020.", 2, "cine/tv"),
    ("HOBBIT", "Bilbo Bolsón, por ejemplo.", 1, "cine/tv"),
    ("YODA", "Pequeño maestro Jedi de orejas puntudas.", 1, "cine/tv"),
    ("JOKER", "Villano payaso de Ciudad Gótica.", 1, "cine/tv"),

    # ---------- IA ----------
    ("CHATGPT", "Chatbot de OpenAI que popularizó la IA.", 1, "IA"),
    ("SIRI", "Asistente de voz del iPhone.", 1, "IA"),
    ("ALEXA", "Asistente de voz de Amazon.", 1, "IA"),
    ("GEMINI", "IA de Google.", 2, "IA"),
    ("CLAUDE", "IA conversacional de Anthropic.", 2, "IA"),
    ("PROMPT", "Instrucción que se le escribe a una IA.", 2, "IA"),
    ("NEURAL", "Red __, base del aprendizaje profundo.", 2, "IA"),
    ("DEEPFAKE", "Video falso generado con IA.", 2, "IA"),

    # ---------- MUNDO ----------
    ("KIMONO", "Vestimenta tradicional japonesa.", 1, "mundo"),
    ("SAFARI", "Excursión para ver animales en África.", 1, "mundo"),
    ("TUNDRA", "Bioma helado sin árboles.", 2, "mundo"),
    ("CARNAVAL", "Fiesta de Río antes de la Cuaresma.", 1, "mundo"),
    ("PIRAMIDE", "Tumba faraónica de base cuadrada.", 1, "mundo"),
    ("GONDOLA", "Bote veneciano de canales.", 2, "mundo"),
    ("SAMBA", "Ritmo brasileño del carnaval.", 1, "música"),
    ("REGGAETON", "Ritmo urbano de Daddy Yankee.", 1, "música"),
    ("BEATLES", "Cuarteto de Liverpool.", 1, "música"),
    ("QUEEN", "Banda de 'Bohemian Rhapsody'.", 1, "música"),
    ("MOZART", "Genio de Salzburgo, autor de 'La Flauta Mágica'.", 1, "música"),
    ("VINILO", "Disco negro que volvió a estar de moda.", 1, "música"),
]


def check():
    import re
    seen = set()
    for w, c, l, t in WORDS:
        assert re.fullmatch(r"[A-ZÑ]{3,11}", w), f"Palabra inválida: {w}"
        assert w not in seen, f"Duplicada: {w}"
        import unicodedata
        plain = unicodedata.normalize("NFD", c.upper())
        plain = "".join(ch for ch in plain if not unicodedata.combining(ch) or ch == "̃")
        plain = unicodedata.normalize("NFC", plain)
        assert c and not re.search(rf"\b{w}\b", plain), f"La pista revela la respuesta: {w}"
        assert l in (1, 2, 3), f"Nivel inválido: {w}"
        seen.add(w)
    print(f"{len(WORDS)} palabras OK")


if __name__ == "__main__":
    check()
